import Image from "next/image";
import Link from "next/link";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function HomePage() {
  const res = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/api/products`);
  const products = await res.json();
  console.log(products);

  return (
    <div className="min-h-screen flex flex-col">
      {/* Hero */}
      <section>
        <div className="relative overflow-hidden bg-base-200">
          {/* Background Pattern */}
          <div className="absolute inset-0">
            <div className="absolute inset-0 bg-gradient-to-br from-primary/10 via-secondary/5 to-accent/10 dark:from-primary/20 dark:via-secondary/10 dark:to-accent/10"></div>
            <div
              className="absolute inset-0 opacity-30 dark:opacity-20"
              style={{
                backgroundImage: `radial-gradient(circle at 1px 1px, rgba(148,163,184,0.3) 1px, transparent 0)`,
                backgroundSize: "24px 24px",
              }}
            ></div>

            {/* Floating Elements */}
            <div className="absolute top-20 left-10 w-20 h-20 bg-gradient-to-r from-primary/20 to-secondary/20 rounded-full blur-xl"></div>
            <div className="absolute top-40 right-20 w-32 h-32 bg-gradient-to-r from-accent/20 to-secondary/20 rounded-full blur-xl"></div>
            <div className="absolute bottom-20 left-1/4 w-24 h-24 bg-gradient-to-r from-accent/20 to-primary/20 rounded-full blur-xl"></div>
          </div>

          <div className="relative container mx-auto px-4 py-24 lg:py-32">
            <div className="max-w-5xl mx-auto text-center space-y-12">
              {/* Hero Content */}
              <div className="space-y-4">
                <h1 className="text-xl md:text-3xl lg:text-5xl font-black leading-tight font-urbanist tracking-tight">
                  <span className="block bg-clip-text text-transparent bg-gradient-to-r from-base-content via-primary to-hover-color dark:from-base-100 dark:via-primary dark:to-accent">
                    Discover the Future of <br /> Shopping
                  </span>
                </h1>

                <p className="text-lg lg:text-xl md:text-2xl text-secondary-content  max-w-3xl mx-auto leading-relaxed">
                  Explore premium products with ease — fast, secure, and built
                  for you.
                </p>
                <div className="flex gap-4 justify-center">
                  <Link href="/products" className="btn btn-primary">
                    Browse Products
                  </Link>
                  <Link href="/login" className="btn btn-outline btn-accent">
                    Get Started
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Product Highlights */}
      <section className="product-highlights p-10">
        <h2 className="text-3xl font-bold mb-6">Featured Products</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {products.slice(0, 3).map((product) => (
            <div
              key={product._id}
              className="border border-neutral-content rounded-lg p-4 shadow hover:shadow-lg space-y-2"
            >
              <Image
                width={300}
                height={300}
                src={product.image}
                alt={product.name}
                className="w-full h-48 object-cover rounded"
              />
              <h3 className="font-semibold mt-2 text-base-content text-xl">
                {product.name}
              </h3>
              <p className="text-sm text-secondary-content">
                {product.description}
              </p>
              <p className="text-green-600 font-bold mt-1">${product.price}</p>

              <Link
                href={`/products/${product?._id}`}
                className="btn btn-primary mt-2"
              >
                View Details
              </Link>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
